- name: install packages
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: insall packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - mysql 
        - nginx
